resources:
  pipelines:
    mvm_pipeline:
      name: "QSR MVM Pipeline [${bundle.target}]"
      channel: PREVIEW
      continuous: false
      catalog: ${var.catalog_name}
      target: ${var.schema_prefix}silver
      libraries:
        - notebook:
            path: ../src/pipeline/mvm_pipeline.py
      serverless: true
      configuration:
        pipeline.catalog: ${var.catalog_name}
        pipeline.schema_prefix: ${var.schema_prefix}
      tags:
        project: qsr-synth-data-generator
