resources:
  pipelines:
    mvm_pipeline:
      name: "QSR MVM Pipeline [${bundle.target}]"
      channel: PREVIEW
      continuous: true
      catalog: ${var.catalog_name}
      target: silver
      libraries:
        - notebook:
            path: ../src/pipeline/mvm_pipeline.py
      serverless: true
      configuration:
        pipeline.catalog: ${var.catalog_name}
      tags:
        project: qsr-synth-data-generator
